CREATE USER coyote identified BY 1234;

GRANT CREATE SESSION TO coyote;

GRANT CREATE TABLE TO coyote;

GRANT unlimited tablespace TO coyote;

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER COYOTE IDENTIFIED BY COYOTE;

CREATE TABLE COYOTE.TB_CATEGORIA ( 
	ID                   INTEGER   NOT NULL,
	NOME                 VARCHAR2(150)   ,
	CONSTRAINT PK_TB_CATEGORIA PRIMARY KEY ( ID ) 
 );

CREATE TABLE COYOTE.TB_VENDAS ( 
	ID                   INTEGER   ,
	ID_PRODUTO           INTEGER   ,
	ID_LOJA              INTEGER   ,
	ID_FUNC              INTEGER   ,
	VALOR_VENDA          FLOAT(2)   ,
	CONSTRAINT UNQ_TB_VENDAS_ID_PRODUTO UNIQUE ( ID_PRODUTO ) ,
	CONSTRAINT UNQ_TB_VENDAS_ID_LOJA UNIQUE ( ID_LOJA ) ,
	CONSTRAINT UNQ_TB_VENDAS_ID_FUNC UNIQUE ( ID_FUNC ) 
 );

CREATE INDEX IDX_TB_VENDAS ON COYOTE.TB_VENDAS ( ID );

CREATE TABLE COYOTE.TB_FUNCIONARIO ( 
	ID                   INTEGER   ,
	NOME                 VARCHAR2(150)   ,
	FUNCAO               VARCHAR2(150)   
 );

CREATE TABLE COYOTE.TB_LOJA ( 
	REGIAO               VARCHAR2(50)   ,
	NOME                 VARCHAR2(150)   ,
	ID                   INTEGER   NOT NULL,
	CONSTRAINT PK_TB_LOJA PRIMARY KEY ( ID ) 
 );

CREATE TABLE COYOTE.TB_PRODUTO ( 
	SKU                  VARCHAR2(300)   ,
	NOME                 VARCHAR2(300)   ,
	ID_CATEGORIA         INTEGER   ,
	ID                   INTEGER   NOT NULL,
	CONSTRAINT UNQ_TB_PRODUTO_ID_CATEGORIA UNIQUE ( ID_CATEGORIA ) ,
	CONSTRAINT PK_TB_PRODUTO PRIMARY KEY ( ID ) 
 );

ALTER TABLE COYOTE.TB_FUNCIONARIO ADD CONSTRAINT FK_TB_FUNCIONARIO_TB_VENDAS FOREIGN KEY ( ID ) REFERENCES COYOTE.TB_VENDAS( ID_FUNC );

ALTER TABLE COYOTE.TB_LOJA ADD CONSTRAINT FK_TB_LOJA_TB_VENDAS FOREIGN KEY ( ID ) REFERENCES COYOTE.TB_VENDAS( ID_LOJA );

ALTER TABLE COYOTE.TB_PRODUTO ADD CONSTRAINT FK_TB_PRODUTO_TB_CATEGORIA FOREIGN KEY ( ID_CATEGORIA ) REFERENCES COYOTE.TB_CATEGORIA( ID );

ALTER TABLE COYOTE.TB_PRODUTO ADD CONSTRAINT FK_TB_PRODUTO_TB_VENDAS FOREIGN KEY ( ID ) REFERENCES COYOTE.TB_VENDAS( ID_PRODUTO );
 